### ISSUE TITLE
Create diagram is not working at all

### ISSUE THREAD

**Issue by synth-me** [pachecot/ebo-script#10]
I tried at windows 10 and the state diagram generation is not working.
I tried different scripts because i thought it was some kind of problem with the types of the input and output but apparently it's actually the plugin which is not working. 
All i did was activate the extension with the folder with a file and all the answer it gives me is the following: 

```html 
stateDiagram
   [*]
```

**Comment by pachecot** [comment]
That looks like what it would generate for an empty program with no lines.

The state diagram is a mermaid file, you would need a plugin to visualize the diagram.
Here is a plugin:
[vscode-mermaid-editor](https://marketplace.visualstudio.com/items?itemName=tomoyukim.vscode-mermaid-editor)

or there is the live editor:
[Mermaid Live](https://mermaid.live/edit#pako:eNpNTzsOgzAMvUrksYILZOjUFTEw1h0s4rSRmgSlzoAQd29IRWF7Hz_bb4ExGgYNHyHhm6NnIo8B5X55tO21ixJTb-2m7FgVXVUyCCX5W5UdZh-OUDhn4nSKxOmU2O5AA56TJ2fKUwsGpRDkxZ4RdIGGLeW3IGBYyyhlicMcRtCSMjeQJ3PU2EU2rmzvfj1r3fULPltWeA)

Do you have a sample program that doesn't work?

This extension just generates mermaid files for SE EBO script programs. 
[SE EBO](https://www.se.com/eg/en/product-range/62111-ecostruxure-building-operation-software/?N=3348538795)


a program like this 
```
MotorOff:
  Goto MotorStart
MotorStart:
  Goto MotorOn
MotorOn:
  Goto MotorStop
MotorStop:
  Goto MotorOff
```

would generate this:
```
stateDiagram
	[*]-->MotorOff
	MotorOff --> MotorStart
	MotorStart --> MotorOn
	MotorOn --> MotorStop
	MotorStop --> MotorOff
```

or

```
'FallThru
Step0:
Step1:
Step2:
Step3:
```

would generate: 
```
stateDiagram
	[*]-->Step0
	Step0-->Step1
	Step1-->Step2
	Step2-->Step3
```

**Comment by synth-me** [comment]
In this one specific case, i'm lots of if conditionals and i guess it's not the case that the plugin won't recognize as a valid way to generate a diagram. Is that correct ?

**Comment by pachecot** [comment]
It should still work if it can process the file. 

Could you share a sample of the code you are having an issue with.

**Comment by synth-me** [comment]
Yes, take this one example: 

```rb
Numeric Input p1, p2 
Numeric Output po1

if p2 < 117 then 
	po1 = 1 
else 
	po1 = 0 
endif

``` 
This one snippet actually works on my real controllers so they're valid code for sure.
i tried both commands to generate the diagram and the result is: 

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>State Diagrams</title>
</head>
<body>

<script type="module">
import mermaid from 'https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.esm.min.mjs';
</script>
</body>
</html>
```

and the mermaid result is the same as that one i sent in here.

**Comment by pachecot** [comment]
The state diagrams are based on the script lines. The script programs and essentially state machines with the line representing the different states. I could review the documentation and see if it could be clearer. 

You could rewrite the program something like this:
```
Numeric Input p1, p2 
Numeric Output po1
State_0:
  if p2 < 117 then Goto State_1
  po1 = 0 
State_1:
  if p2 >= 117 then Goto State_0
  po1 = 1 
```

Curious what you were expecting.
