### ISSUE TITLE
Select Case Issues

### ISSUE THREAD

**Issue by Tehbeardedgamer** [pachecot/ebo-script#8]
Using Select Case breaks link between declared variables and shows issues as bad case statement. However it does work in EBO workstation.

```
NUMERIC INPUT EXA_TEMP,OA_TEMP,WHEEL_DP_STATUS,EXA_DAMPER_CMD_BYPASS,OA_DAMPER_CMD_BYPASS,SA_TEMP, WHEEL,OA_WHEEL_SA_TEMP,EXA_DAMPER_POS,EXA_DAMPER_POS_BYPASS,OCC_SCHEDULE
NUMERIC OUTPUT COOLING_MODE, ECONCOOLING_MODE, ECONOMIZER_MODE, HEATING_MODE,OCCUPIED_MODE,UNOCCUPIED_MODE

'OCCUPIED_MODE
Select Case True
    Case OCC_SCHEDULE = on
        OCCUPIED_MODE = on
        UNOCCUPIED_mode = off
    Case Else
        UNOCCUPIED_mode = on
        OCCUPIED_MODE = off
EndSelect
'COOLING MODE
Select Case True
    Case OA_TEMP > EXA_TEMP
        COOLING_MODE = on
    Case Else
        COOLING_MODE = off
EndSelect
'ECONOMIZER COOLING MODE
Select Case True
    Case OA_TEMP < EXA_TEMP And OA_TEMP > SA_TEMP
        ECONCOOLING_MODE = on
    Case Else
        ECONCOOLING_MODE = off
EndSelect
'ECONOMIZER MODE
Select Case True
    Case OA_TEMP < SA_TEMP
        ECONOMIZER_MODE = on
    Case Else
        ECONOMIZER_MODE = off
EndSelect
'HEATING MODE
Select Case True
    Case Wheel = on And EXA_DAMPER_POS_BYPASS = off And OA_WHEEL_SA_TEMP < (SA_TEMP - 2)
        HEATING_MODE = on
    Case Else
        HEATING_MODE = off
EndSelect


Wait 60`
```

**Comment by pachecot** [comment]
Thats a different code style. I don't think that's allowed in many languages, so there may be better way to express your intent. 

It does seem to be valid script programming, so I updated the extension.

Thanks for reporting the issue.

**Comment by Tehbeardedgamer** [comment]
Sorry for commenting like this but I don't know of another way to ask, But do you happen to have a discord or other social handle I could possibly message you through? I was wondering if possibly I might be able to ask some questions about EBO Script and learn from your knowledge.

**Comment by pachecot** [comment]
Not a problem. Not to active on most of the social platforms. Currently the Schneider Electric forum might be best place to contact me regarding script programming. User there is TomP or Tom Pacheco you can DM me.
